import type { Metadata } from "next";
// @ts-ignore
import "@/src/app/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Public({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="p-4 bg-gray-100">
          <nav>
            {/* Adicione links de navegação aqui se necessário */}
          </nav>
        </header>
        <main className="min-h-screen">
          {children}
        </main>
        <footer className="p-4 bg-gray-100 text-center">
          <p>&copy; 2025 - Todos os direitos reservados</p>
        </footer>
      </body>
    </html>
  );
}
